### ISSUE TITLE
Problem with position

### ISSUE THREAD

**Issue by chassain** [cowboysdude/MMM-rfacts#10]
Hello cowboysdude,

I'm working with your funny module, translate in french. Sometimes, the translation is on late but it doesn't matter. The problem is about the position. I'm trying to display the writte on the right but the module is always on the left... thanks for idea.
have a good day

**Comment by chassain** [comment]
Hello,

The position is ok now after many reboot..but still the problem with traduction in french...many times in english..If you have an idea. Thanks

**Comment by cowboysdude** [comment]
Sorry it's taken so long.  I will test it tomorrow evening.  It's late here now :)

**Comment by chassain** [comment]
Don' t worry..it's ok after a new npm install...You can sleep well..:)
