### ISSUE TITLE
promise.all() rejection

### ISSUE THREAD

**Issue by theramez** [cowboysdude/MMM-rfacts#4]
greetings @cowboysdude ,
module languages other than english is not working after some investigation discovered that `promise.all()` function always return a rejection
 ```
{node:1148} UnhandeledPromiseRejectWarning: Unhandeled promise rejection {rejection id: 1}: Error
{node:1148} [DEP0018] DeprecationWarning: Unhandeled promise rejection are deprecated. In the future, promise rejections that are not handeled will terminate the Node.js process with a non-zer exit code.
```
maybe something has changed in dependency `require(google-translate-api)` don't really know as am not a programmer.

thanks in advance..

**Comment by cowboysdude** [comment]
Is fixed.

**Comment by lavolp3** [comment]
Seems not to be fixed. I have the same error using german language

**Comment by lavolp3** [comment]
Sorry it's a new error now:
`0|mm       | (node:12168) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'refs' of undefined
`

**Comment by cowboysdude** [comment]
Yes I saw that and am working on it :)  Sorry, hope to have it resolved soon!

**Comment by cowboysdude** [comment]
I just ran it in 'de' and it worked........so not sure what's going on.  What language is in your config.js?

**Comment by lavolp3** [comment]
it's 'de'
I can post the config when I'm back home again.

**Comment by cowboysdude** [comment]
Ok
