### ISSUE TITLE
git link needs a tiny update ;)

### ISSUE THREAD

**Issue by daVid0n** [cowboysdude/MMM-rfacts#5]
Hey there,

just wanted to let you know that the posted git-link needs one more letter at its end (an s):

original link in description:    git clone https://github.com/cowboysdude/MMM-rfact

corrected one:                       git clone https://github.com/cowboysdude/MMM-rfacts

Cheers and merry christmas,
daVid

**Comment by cowboysdude** [comment]
Thank you and Merry Christmas to you too! :)
